import java.awt.*; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EmptyStackException;
import javax.swing.*; 
public class MyGridLayout{ 
    JFrame f;
    JLabel lbl;
    JTextField t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46,t47,t48,t49,t50,t51,t52,t53,t54,t55,t56,t57,t58,t59,t60,t61,t62,t63,t64,t65,t66,t67,t68,t69,t70,t71,t72,t73,t74,t75,t76,t77,t78,t79,t80,t81; 
    MyGridLayout(){
        f=new JFrame();
        lbl = new JLabel("");
        int[] intArray;
        intArray = new int[]{4,3,5,2,6,9,7,8,1,6,8,2,5,7,1,4,9,3,1,9,7,8,3,4,5,6,2,8,2,6,1,9,5,3,4,7,3,7,4,6,8,2,9,1,5,9,5,1,7,4,3,6,2,8,5,1,9,3,2,6,8,7,4,2,4,8,9,5,7,1,3,6,7,6,3,4,1,8,2,5,9}; 
        JTextField t1=new JTextField("");
        t1.setBackground(Color.green);
        t1.setEditable(true);
        JTextField t2=new JTextField(""); 
        t2.setBackground(Color.green);
        t2.setEditable(true);
        JTextField t3=new JTextField(""); 
        t3.setBackground(Color.green);
        t3.setEditable(true); 
        JTextField t4=new JTextField("2");
        t4.setForeground(Color.red);
        t4.setEditable(false); 
        JTextField t5=new JTextField("6");
        t5.setForeground(Color.red);
        t5.setEditable(false); 
        JTextField t6=new JTextField("");
        t6.setEditable(true);
        JTextField t7=new JTextField("7");
        t7.setForeground(Color.red);
        t7.setBackground(Color.green);
        t7.setEditable(false);
        JTextField t8=new JTextField("");
        t8.setBackground(Color.green);
        t8.setEditable(true); 
        JTextField t9=new JTextField("1");
        t9.setForeground(Color.red);
        t9.setBackground(Color.green);
        t9.setEditable(false); 
        JTextField t10=new JTextField("6"); 
        t10.setForeground(Color.red);
        t10.setEditable(false);
        t10.setBackground(Color.green);
        JTextField t11=new JTextField("8");
        t11.setForeground(Color.red);
        t11.setBackground(Color.green);
        t11.setEditable(false); 
        JTextField t12=new JTextField("");
        t12.setBackground(Color.green);
        t12.setEditable(true); 
        JTextField t13=new JTextField(""); 
        t13.setEditable(true);
        JTextField t14=new JTextField("7");
        t14.setForeground(Color.red); 
        t14.setEditable(false); 
        JTextField t15=new JTextField(""); 
        t15.setEditable(true); 
        JTextField t16=new JTextField("");
        t16.setBackground(Color.green); 
        t16.setEditable(true); 
        JTextField t17=new JTextField("9");
        t17.setForeground(Color.red);
        t17.setForeground(Color.red);
        t17.setBackground(Color.green);
        t17.setEditable(false); 
        JTextField t18=new JTextField("");
        t18.setBackground(Color.green);
        t18.setEditable(true); 
        JTextField t19=new JTextField("1");
        t19.setForeground(Color.red); 
        t19.setBackground(Color.green);
        t19.setEditable(false); 
        JTextField t20=new JTextField("9");
        t20.setForeground(Color.red);
        t20.setBackground(Color.green);
        t20.setEditable(false); 
        JTextField t21=new JTextField("");
        t21.setBackground(Color.green);
        t21.setEditable(true); 
        JTextField t22=new JTextField("");
        t22.setEditable(true); 
        JTextField t23=new JTextField("");
        t23.setEditable(true); 
        JTextField t24=new JTextField("4");
        t24.setForeground(Color.red);
        t24.setEditable(false); 
        JTextField t25=new JTextField("5"); 
        t25.setForeground(Color.red);
        t25.setBackground(Color.green);
        t25.setEditable(false); 
        JTextField t26=new JTextField("");
        t26.setBackground(Color.green);
        t26.setEditable(true); 
        JTextField t27=new JTextField("");
        t27.setBackground(Color.green); 
        t27.setEditable(true); 
        JTextField t28=new JTextField("8"); 
        t28.setForeground(Color.red);
        t28.setEditable(false); 
        JTextField t29=new JTextField("2");
        t29.setForeground(Color.red);
        t29.setEditable(false); 
        JTextField t30=new JTextField(""); 
        t30.setEditable(true); 
        JTextField t31=new JTextField("1");
        t31.setForeground(Color.red);
        t31.setBackground(Color.green);
        t31.setEditable(false); 
        JTextField t32=new JTextField("");
        t32.setBackground(Color.green);
        t32.setEditable(true); 
        JTextField t33=new JTextField("");
        t33.setBackground(Color.green);
        t33.setEditable(true); 
        JTextField t34=new JTextField(""); 
        t34.setEditable(true); 
        JTextField t35=new JTextField("4");
        t35.setForeground(Color.red);
        t35.setEditable(false); 
        JTextField t36=new JTextField("");
        t36.setEditable(true); 
        JTextField t37=new JTextField(""); 
        t37.setEditable(true); 
        JTextField t38=new JTextField(""); 
        t38.setEditable(true); 
        JTextField t39=new JTextField("4");
        t39.setForeground(Color.red); 
        t39.setEditable(false); 
        JTextField t40=new JTextField("6"); 
        t40.setForeground(Color.red);
        t40.setBackground(Color.green);
        t40.setEditable(false); 
        JTextField t41=new JTextField("");
        t41.setBackground(Color.green);
        t41.setEditable(true); 
        JTextField t42=new JTextField("2");
        t42.setForeground(Color.red);
        t42.setBackground(Color.green);
        t42.setEditable(false); 
        JTextField t43=new JTextField("9"); 
        t43.setForeground(Color.red);
        t43.setEditable(false); 
        JTextField t44=new JTextField(""); 
        t44.setEditable(true); 
        JTextField t45=new JTextField("");
        t45.setEditable(true); 
        JTextField t46=new JTextField("");
        t46.setEditable(true); 
        JTextField t47=new JTextField("5");
        t47.setForeground(Color.red);
        t47.setEditable(false); 
        JTextField t48=new JTextField("");
        t48.setEditable(true); 
        JTextField t49=new JTextField("");
        t49.setBackground(Color.green);
        t49.setEditable(true); 
        JTextField t50=new JTextField(""); 
        t50.setBackground(Color.green);
        t50.setEditable(true); 
        JTextField t51=new JTextField("3"); 
        t51.setForeground(Color.red);
        t51.setBackground(Color.green);
        t51.setEditable(false); 
        JTextField t52=new JTextField(""); 
        t52.setEditable(true); 
        JTextField t53=new JTextField("2"); 
        t53.setForeground(Color.red);
        t53.setEditable(false); 
        JTextField t54=new JTextField("8");
        t54.setForeground(Color.red);
        t54.setEditable(false); 
        JTextField t55=new JTextField("");
        t55.setBackground(Color.green); 
        t55.setEditable(true); 
        JTextField t56=new JTextField("");
        t56.setBackground(Color.green);
        t56.setEditable(true); 
        JTextField t57=new JTextField("9"); 
        t57.setForeground(Color.red);
        t57.setBackground(Color.green);
        t57.setEditable(false); 
        JTextField t58=new JTextField("3");
        t58.setForeground(Color.red);
        t58.setEditable(false); 
        JTextField t59=new JTextField("");
        t59.setEditable(true); 
        JTextField t60=new JTextField(""); 
        t60.setEditable(true); 
        JTextField t61=new JTextField("");
        t61.setBackground(Color.green);
        t61.setEditable(true); 
        JTextField t62=new JTextField("7");
        t62.setForeground(Color.red);
        t62.setBackground(Color.green);
        t62.setEditable(false); 
        JTextField t63=new JTextField("4");
        t63.setForeground(Color.red);
        t63.setBackground(Color.green);
        t63.setEditable(false); 
        JTextField t64=new JTextField("");
        t64.setBackground(Color.green);
        t64.setEditable(true); 
        JTextField t65=new JTextField("4");
        t65.setForeground(Color.red);
        t65.setBackground(Color.green);
        t65.setEditable(false); 
        JTextField t66=new JTextField(""); 
        t66.setBackground(Color.green);
        t66.setEditable(true); 
        JTextField t67=new JTextField("");
        t67.setEditable(true); 
        JTextField t68=new JTextField("5"); 
        t68.setForeground(Color.red);
        t68.setEditable(false); 
        JTextField t69=new JTextField(""); 
        t69.setEditable(true); 
        JTextField t70=new JTextField("");
        t70.setBackground(Color.green);
        t70.setEditable(true); 
        JTextField t71=new JTextField("3"); 
        t71.setForeground(Color.red);
        t71.setBackground(Color.green);
        t71.setEditable(false); 
        JTextField t72=new JTextField("6");
        t72.setForeground(Color.red);
        t72.setBackground(Color.green);
        t72.setEditable(false); 
        JTextField t73=new JTextField("7");
        t73.setForeground(Color.red);
        t73.setBackground(Color.green);
        t73.setEditable(false); 
        JTextField t74=new JTextField("");
        t74.setBackground(Color.green);
        t74.setEditable(true); 
        JTextField t75=new JTextField("3"); 
        t75.setForeground(Color.red);
        t75.setBackground(Color.green);
        t75.setEditable(false); 
        JTextField t76=new JTextField("");
        t76.setEditable(true); 
        JTextField t77=new JTextField("1");
        t77.setForeground(Color.red);
        t77.setEditable(false); 
        JTextField t78=new JTextField("8"); 
        t78.setForeground(Color.red);
        t78.setEditable(false); 
        JTextField t79=new JTextField(""); 
        t79.setEditable(true); 
        t79.setBackground(Color.green);
        JTextField t80=new JTextField(""); 
        t80.setBackground(Color.green);
        t80.setEditable(true); 
        JTextField t81=new JTextField("");
        t81.setBackground(Color.green);
        t81.setEditable(true); 
        f.add(t1);f.add(t2);f.add(t3);f.add(t4);f.add(t5); 
        f.add(t6);f.add(t7);f.add(t8);f.add(t9); f.add(t10); 
        f.add(t11);f.add(t12);f.add(t13);f.add(t14);f.add(t15);
        f.add(t16);f.add(t17);f.add(t18);f.add(t19);f.add(t20);
        f.add(t21);f.add(t22);f.add(t23);f.add(t24);f.add(t25); 
        f.add(t26);f.add(t27);f.add(t28);f.add(t29); f.add(t30); 
        f.add(t31);f.add(t32);f.add(t33);f.add(t34);f.add(t35);
        f.add(t36);f.add(t37);f.add(t38);f.add(t39);f.add(t40);
        f.add(t41);f.add(t42);f.add(t43);f.add(t44);f.add(t45); 
        f.add(t46);f.add(t47);f.add(t48);f.add(t49); f.add(t50);
        f.add(t51);f.add(t52);f.add(t53);f.add(t54);f.add(t55); 
        f.add(t56);f.add(t57);f.add(t58);f.add(t59); f.add(t60);
        f.add(t61);f.add(t62);f.add(t63);f.add(t64);f.add(t65); 
        f.add(t66);f.add(t67);f.add(t68);f.add(t69); f.add(t70);
        f.add(t71);f.add(t72);f.add(t73);f.add(t74);f.add(t75);
        f.add(t76);f.add(t77);f.add(t78);f.add(t79);f.add(t80);
        f.add(t81);
        f.setLayout(new GridLayout(10,9)); 
 //setting grid layout of 9 rows and 9 columns 
        f.setSize(350,400); 
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        final JButton b = new JButton("submit");
        lbl.setBackground(Color.red);
        f.add(lbl);
        b.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                try{
                    if (b.isEnabled()) {
                        int[] intArray1;
                        intArray1 = new int[81];
                        intArray1[0]=Integer.parseInt(t1.getText());
                        intArray1[1]=Integer.parseInt(t2.getText());
                        intArray1[2]=Integer.parseInt(t3.getText());
                        intArray1[3]=2;
                        intArray1[4]=6;
                        intArray1[5]=Integer.parseInt(t6.getText());
                        intArray1[6]=7;
                        intArray1[7]=Integer.parseInt(t8.getText());
                        intArray1[8]=1;
                        intArray1[9]=6;
                        intArray1[10]=8;
                        intArray1[11]=Integer.parseInt(t12.getText());
                        intArray1[12]=Integer.parseInt(t13.getText());
                        intArray1[13]=7;
                        intArray1[14]=Integer.parseInt(t15.getText());
                        intArray1[15]=Integer.parseInt(t16.getText());
                        intArray1[16]=9;
                        intArray1[17]=Integer.parseInt(t18.getText());
                        intArray1[18]=1;;
                        intArray1[19]=9;
                        intArray1[20]=Integer.parseInt(t21.getText());
                        intArray1[21]=Integer.parseInt(t22.getText());
                        intArray1[22]=Integer.parseInt(t23.getText());
                        intArray1[23]=4;
                        intArray1[24]=5;
                        intArray1[25]=Integer.parseInt(t26.getText());
                        intArray1[26]=Integer.parseInt(t27.getText());
                        intArray1[27]=8;
                        intArray1[28]=2;
                        intArray1[29]=Integer.parseInt(t30.getText());
                        intArray1[30]=1;
                        intArray1[31]=Integer.parseInt(t32.getText());
                        intArray1[32]=Integer.parseInt(t33.getText());
                        intArray1[33]=Integer.parseInt(t34.getText());
                        intArray1[34]=4;
                        intArray1[35]=Integer.parseInt(t36.getText());
                        intArray1[36]=Integer.parseInt(t37.getText());
                        intArray1[37]=Integer.parseInt(t38.getText());
                        intArray1[38]=4;
                        intArray1[39]=6;
                        intArray1[40]=Integer.parseInt(t41.getText());
                        intArray1[41]=2;
                        intArray1[42]=9;
                        intArray1[43]=Integer.parseInt(t44.getText());
                        intArray1[44]=Integer.parseInt(t45.getText());
                        intArray1[45]=Integer.parseInt(t46.getText());
                        intArray1[46]=5;
                        intArray1[47]=Integer.parseInt(t48.getText());
                        intArray1[48]=Integer.parseInt(t49.getText());
                        intArray1[49]=Integer.parseInt(t50.getText());
                        intArray1[50]=3;
                        intArray1[51]=Integer.parseInt(t52.getText());
                        intArray1[52]=2;
                        intArray1[53]=8;
                        intArray1[54]=Integer.parseInt(t55.getText());
                        intArray1[55]=Integer.parseInt(t56.getText());
                        intArray1[56]=9;
                        intArray1[57]=3;
                        intArray1[58]=Integer.parseInt(t59.getText());
                        intArray1[59]=Integer.parseInt(t60.getText());
                        intArray1[60]=Integer.parseInt(t61.getText());
                        intArray1[61]=7;
                        intArray1[62]=4;
                        intArray1[63]=Integer.parseInt(t64.getText());
                        intArray1[64]=4;
                        intArray1[65]=Integer.parseInt(t66.getText());
                        intArray1[66]=Integer.parseInt(t67.getText());
                        intArray1[67]=5;
                        intArray1[68]=Integer.parseInt(t69.getText());
                        intArray1[69]=Integer.parseInt(t70.getText());
                        intArray1[70]=3;
                        intArray1[71]=6;
                        intArray1[72]=7;
                        intArray1[73]=Integer.parseInt(t74.getText());
                        intArray1[74]=3;
                        intArray1[75]=Integer.parseInt(t76.getText());
                        intArray1[76]=1;
                        intArray1[77]=8;
                        intArray1[78]=Integer.parseInt(t79.getText());
                        intArray1[79]=Integer.parseInt(t80.getText());
                        intArray1[80]=Integer.parseInt(t81.getText());
                        int count=0;
                        for(int i=0;i<intArray1.length;i++){
                            if(intArray[i]==intArray1[i])
                            {
                                count=count+1;
                            }
                        }
                        if(count==81)
                        {
                            lbl.setText("sudoku completed");
                        }
                        else
                        {
                            lbl.setText("lost the game");
                        }
                    }
                }
                catch(NumberFormatException e)
                {
                    lbl.setText("enter all the fields");
                }
                if (!b.isEnabled()) {
                    System.out.println("enter all fields");
                }
            }
        });
        f.add(b);
    } 
    public static void main(String[] args) { 
        new MyGridLayout(); 
    } 
} 
